project/miscosas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('logout/', views.logout_view),
    path('signup', views.signup),
    path('usuarios/', views.users_view),
    path('usuarios/<string>/', views.one_user),
    path('alimentadores/', views.alimentadores),
    path('alimentadores/<string>/', views.aliment),
    path('item/<string>/', views.item),
    path('', views.index),
    path('info/', views.info),
]

project/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView as login
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('miscosas/', include('miscosas.urls')),
    path('login', login.as_view()),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/miscosas/models.py
from django.db import models
from django.contrib.auth.models import User

class Perfil(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    foto = models.ImageField(upload_to='miscosas/images/', default = "/miscosas/images/foto.jpg")
    MODO = (
        ('l', 'Ligero'),
        ('o', 'Oscuro'),
    )
    modo_pagina = models.CharField(max_length=1, choices=MODO, blank=True, default='l', help_text='Modo de la pagina')
    TAMANO = (
        ('p', 'Pequeña'),
        ('m', 'Mediana'),
        ('g', 'Grande'),
    )
    tamano_letra = models.CharField(max_length=1, choices=TAMANO, blank=True, default='m', help_text='Tamaño de la letra')
    def __str__(self):
        return self.usuario.username

class Alimentador(models.Model):
    id_channel = models.CharField(max_length=200)
    titulo = models.CharField(max_length=64)
    enlace = models.URLField()
    puntuacion = models.IntegerField(default=0)
    select = models.BooleanField(default = True)
    def __str__(self):
        return self.id_channel

class Item(models.Model):
    alimentador = models.ForeignKey(Alimentador, on_delete=models.CASCADE)
    id_item = models.CharField(max_length=256) #Cambiar nombre
    titulo = models.CharField(max_length=64) #Titulo
    enlace = models.URLField()
    description = models.CharField(max_length=512, default = "")
    votos_pos = models.IntegerField(default=0)
    votos_neg = models.IntegerField(default=0)

    def __str__(self):
        return self.titulo

class Comentario(models.Model):
    usuario = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    cuerpo = models.TextField(blank=False, max_length=256)
    foto = models.ImageField(upload_to='miscosas/images/', default = "no photo")
    fecha = models.DateTimeField('publicado')
    def __str__(self):
        return self.usuario.usuario.username + " --> " + self.item.titulo


class Item_votados(models.Model):
     usuario = models.ForeignKey(User, on_delete=models.CASCADE)
     item = models.ForeignKey(Item, on_delete=models.CASCADE)
     voto = models.IntegerField(default=0)

     def __str__(self):
         return self.usuario.username + " --> " + self.item.titulo

project/miscosas/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import  Alimentador, Perfil, Comentario

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class ModoForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ('foto','modo_pagina','tamano_letra',)

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ('cuerpo','foto',)

project/miscosas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.http import HttpResponse
from django.utils import timezone
from .models import  Alimentador, Item, Perfil, Item_votados
from .forms import UserForm, ModoForm, ComentarioForm
from .youtube_handler import YTChannel
from .last_handler import LastChannel
from .reddit_handler import RedditChannel
from .key import LASTFM_APIKEY
import urllib
import urllib.request
import operator
from django.core import serializers

def pagina_error(request):
    if request.user.is_authenticated:
        perfil = Perfil.objects.get(usuario = request.user)
    else:
        perfil = None
    context = { 'titulo': "Error 404",
                'perfil': perfil,
            }
    pagina = render(request, 'miscosas/error.html', context)
    pagina.status_code = 404
    return pagina

def best_items(request):
    best = {}
    lista_items = []
    items = Item.objects.all()
    for string in items:
        votos = Item_votados.objects.filter(item = string)
        votos_pos = votos.filter(voto = 1).count()
        votos_neg = votos.filter(voto = -1).count()
        total = votos_pos - votos_neg
        best[string.id_item] = total
    orden = sorted(best.items(), key=operator.itemgetter(1), reverse = True)
    orden = orden[0:10]
    for id, votos in orden:
        try:
            item = Item.objects.get(id_item=id)
        except Item.DoesNotExist:
            pagina_error(request)
        lista_items.append(item)
    return lista_items

def last_items(perfil):
    lista_items = []
    items = Item_votados.objects.filter(usuario = perfil.usuario)
    for item in items:
        lista_items.append(item)
    lista_items.reverse()
    lista_items = lista_items[:5]
    return lista_items

def index(request):
    items = best_items(request)
    if request.user.is_authenticated:
        perfil = Perfil.objects.get(usuario = request.user)
        ultimos_items = last_items(perfil)
    else:
        perfil = None
        ultimos_items = None
    context = { 'titulo': "Inicio",
                'alimentadores': Alimentador.objects.filter(select = True),
                'items': items,
                'ultimos_votos':ultimos_items,
                'perfil': perfil,
            }
    formato =  request.GET.get('format')
    if formato == 'xml':
        return render(request, "miscosas/index.xml", context,  content_type='text/xml')
    elif formato == 'json':
        context = [ *items,
                    *Alimentador.objects.filter(select = True),
                    *ultimos_items,
                    ]
        contenidos = serializers.serialize('json', context)
        return HttpResponse(contenidos, content_type="application/json")
    return render(request, 'miscosas/index.html', context)


def add_aliment(request):
    alimentador = request.POST["aliment"]
    id = request.POST['id']
    if alimentador == "actualizar":
        if id[0] == "r":
            alimentador = 'Reddit'
            id = id.replace('_', '/')
        elif id[0] == "U":
            alimentador = 'Youtube'
        else:
            alimentador = 'LastFM'
    try:
        if alimentador == 'Youtube':
            url = 'https://www.youtube.com/feeds/videos.xml?channel_id=' \
            + id
            xmlStream = urllib.request.urlopen(url)
            YTChannel(xmlStream)
        elif alimentador == 'LastFM':
            id = id.replace(' ', '+')
            url = 'http://ws.audioscrobbler.com/2.0/?method=artist.gettopalbums&artist=' + \
            id + '&api_key=' + LASTFM_APIKEY
            xmlStream = urllib.request.urlopen(url)
            LastChannel(xmlStream)
        elif alimentador == 'Reddit':
            url = "https://www.reddit.com/" + id + ".rss"
            xmlStream = urllib.request.urlopen(url)
            RedditChannel(xmlStream)
    except:
        return True
    return False

def alimentadores(request):
    if request.method == "POST":
        if add_aliment(request):
            return pagina_error(request)
    try:
        alimentadores = Alimentador.objects.all()
    except Alimentador.DoesNotExist:
        return pagina_error(request)
    if request.user.is_authenticated:
        perfil = Perfil.objects.get(usuario = request.user)
    else:
        perfil = None
    context = {"alimentadores": alimentadores,
                "titulo": "Alimentadores",
                'perfil': perfil,
                }
    formato =  request.GET.get('format')
    if formato == 'xml':
        return render(request, "miscosas/alimentadores.xml", context, content_type='text/xml')
    elif formato == 'json':
        context = [ *alimentadores,
                    ]
        contenidos = serializers.serialize('json', context)
        return HttpResponse(contenidos, content_type="application/json")
    return render(request, 'miscosas/alimentadores.html', context)

def aliment(request, string):
    try:
        aliment = Alimentador.objects.get(id_channel=string)
        if request.method == "POST":
            value = request.POST['submit']
            if value == "Deseleccionar":
                aliment.select = False
            elif value == "Seleccionar":
                aliment.select = True
            aliment.save()
            if "redirect" in request.POST:
                return redirect('/miscosas/'+ request.POST['redirect'])
    except Alimentador.DoesNotExist:
        return pagina_error(request)
    if request.user.is_authenticated:
        perfil = Perfil.objects.get(usuario = request.user)
    else:
        perfil = None
    context = {"alimentador": aliment,
                "titulo": "Alimentador",
                'perfil': perfil,
                }
    formato =  request.GET.get('format')
    if formato == 'xml':
        return render(request, 'miscosas/alimentador.xml', context, content_type='text/xml')
    elif formato == 'json':
        context = [ aliment,
                    ]
        contenidos = serializers.serialize('json', context)
        return HttpResponse(contenidos, content_type="application/json")
    return render(request, 'miscosas/alimentador.html', context)

def votos(item, value, user):
    try:
        voto_user = Item_votados.objects.filter(usuario = user.id).get(item = item.id)
        if voto_user.voto == 1 and value == "dislike":
            item.votos_pos = item.votos_pos - 1
            item.votos_neg = item.votos_neg + 1
            voto_user.delete()
            voto_user = Item_votados(usuario = user, item = item, voto = -1)
            item.alimentador.puntuacion = item.alimentador.puntuacion - 2
            voto_user.save()
        elif voto_user.voto == -1 and value == "like":
            item.votos_pos = item.votos_pos + 1
            item.votos_neg = item.votos_neg - 1
            voto_user.delete()
            voto_user = Item_votados(usuario = user, item = item, voto = 1)
            item.alimentador.puntuacion = item.alimentador.puntuacion + 2
            voto_user.save()
        elif (voto_user.voto == 1 and value == "like"):
            item.votos_pos = item.votos_pos - 1
            item.alimentador.puntuacion = item.alimentador.puntuacion - 1
            voto_user.delete()
        elif (voto_user.voto == -1 and value == "dislike"):
            item.votos_neg = item.votos_neg - 1
            item.alimentador.puntuacion = item.alimentador.puntuacion + 1
            voto_user.delete()
    except Item_votados.DoesNotExist:
        voto_user = Item_votados(usuario = user, item = item, voto = 0)
        if value == "like":
            voto_user.voto = 1
            item.votos_pos = item.votos_pos + 1
            item.alimentador.puntuacion = item.alimentador.puntuacion + 1
        elif value == "dislike":
            voto_user.voto = -1
            item.votos_neg = item.votos_neg + 1
            item.alimentador.puntuacion = item.alimentador.puntuacion - 1
        voto_user.save()
    item.save()
    item.alimentador.save()

def add_new_comment(request, string, item):
    try:
        user = User.objects.get(username = request.user.username)
        perfil = Perfil.objects.get(usuario=request.user)
    except Perfil.DoesNotExist:
        return pagina_error(request)
    form = ComentarioForm(request.POST, request.FILES)
    if form.is_valid():
        comentario = form.save(commit=False)
        comentario.usuario = perfil
        comentario.item = item
        if "foto" in request.FILES:
            comentario.foto = request.FILES['foto']
        comentario.fecha = timezone.now()
        comentario.save()

def item(request, string):
    item = get_object_or_404(Item, id_item=string)
    if request.method == "POST":
        if "comment" in request.POST:
            add_new_comment(request, string, item)
        else:
            value = request.POST['submit']
            votos(item, value, request.user)
            if "redirect" in request.POST:
                return redirect('/miscosas/'+ request.POST['redirect'])

    form_c =  ComentarioForm()
    if request.user.is_authenticated:
        perfil = Perfil.objects.get(usuario = request.user)
        try:
            item_votado = Item_votados.objects.get(usuario = request.user, item = item)
        except:
            item_votado = None
    else:
        perfil = None
        item_votado = None
    context = {"item": item,
                "titulo": "Item",
                'perfil': perfil,
                "form_c": form_c,
                'item_votado': item_votado,
                }
    formato =  request.GET.get('format')
    comment = request.GET.get('comment')
    if formato == 'xml':
        if comment == 'true':
            return render(request, 'miscosas/item_comment.xml', context, content_type='text/xml')
        else:
            return render(request, 'miscosas/item.xml', context, content_type='text/xml')
    elif formato == 'json':
        if item_votado != None:
            context = [ item,

project/miscosas/templates/miscosas/alimentador.html
{% extends 'miscosas/base.html' %}

  {% block menu %}
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/">Inicio</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/alimentadores/">Alimentadores</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/usuarios/">Usuarios</a>
    </li>
    <li class="nav-item disabled">
      <a class="nav-link" href="/miscosas/info/">Información</a>
    </li>
  {% endblock %}

  {% block contenido %}
    <div class="content container texto" id = 'alimentador'>
      <h2>El canal seleccionado es: {{alimentador.titulo}}</h2>
      El Canal está:
      <form action="" method='POST'> {% csrf_token %}
      {% if alimentador.select %}
        Seleccionado
          <input type="submit"  class="save btn btn-info boton" name="submit" value='Deseleccionar'>
      {% else %}
        No seleccionado
          <input type="submit"  class="save btn btn-info boton" name="submit" value='Seleccionar'>
      {% endif %}
      </form>

      <a href={{alimentador.enlace}}>{{ alimentador.enlace }}</a>
      <h5>Puntuación: {{alimentador.puntuacion}}</h5>
      <h5>Lista de videos totales: {{alimentador.item_set.count}}</h5>

      <div class="texto" id="items">
        {% for item in alimentador.item_set.all %}
          <li><h5><a href="/miscosas/item/{{item.id_item}}">{{ item.titulo }}</a></h5></li>
          <h5><a href={{item.enlace}}>{{ item.enlace }}</a></h5>
          {% endfor %}
      </div>
    </div>
  {% endblock %}

project/miscosas/templates/miscosas/alimentadores.html
{% extends 'miscosas/base.html' %}
    {% block menu %}
      <li class="nav-item">
        <a class="nav-link" href="/miscosas/">Inicio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/miscosas/usuarios/">Usuarios</a>
      </li>
      <li class="nav-item disabled">
        <a class="nav-link" href="/miscosas/info/">Información</a>
      </li>
    {% endblock %}

    {% block contenido %}
      <div  class="texto" id = 'lista alimentadores'>
        {% for aliment in alimentadores %}
          <br>
          <li><h3><strong><a href="/miscosas/alimentadores/{{aliment.id_channel}}">
            {{ aliment.titulo }}</a></strong></h3></li>
          <a href={{aliment.enlace}}>{{aliment.enlace }}</a>
          <h6><strong>Número de videos:</strong> {{aliment.item_set.count}}</h6>
          <h6><strong>Puntuación: </strong>{{aliment.puntuacion}}</h6>
          <form action="{{aliment.id_channel}}/" method='POST'> {% csrf_token %}
              {% if aliment.select %}
                <input type="submit" class="save btn btn-info boton" name="submit" value='Deseleccionar'>
              {% else %}
                <input type="submit"  class="save btn btn-info boton" name="submit" value='Seleccionar'>
              {%endif %}
              <input type="hidden" name="redirect" id="redirect"   value="alimentadores/">
          </form>
        {% endfor %}
      </div>
    {% endblock %}

project/miscosas/templates/miscosas/error.html
{% extends 'miscosas/base.html' %}
{% load static%}
  {% block menu %}
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/">Inicio</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/alimentadores/">Alimentadores</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/usuarios/">Usuarios</a>
    </li>
    <li class="nav-item disabled">
      <a class="nav-link" href="/miscosas/info/">Información</a>
    </li>
  {% endblock %}

  {% block contenido %}
    <div  id ="Error">
    <img src="{% static "miscosas/error_404.jpg" %}"  alt="Foto"  width="500" class="img-rounded rounded-sm">
    </div>
    <h4>Ha habido un error con la pagina solicitada, pulse para volver a la página principal.</h4>
    <a type="button" href="/miscosas/" class="btn btn-primary btn-lg btn-block">Pagina principal</a>
  {% endblock %}

project/miscosas/templates/miscosas/formulario.html
{% extends 'miscosas/base.html' %}
  {% block contenido %}
    <body>
    <h2>New content</h2>
    <form method="POST"  class="YouTube-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-info">Guardar</button>
    </form>
    </body>
  </html>
  {% endblock %}

project/miscosas/templates/miscosas/info.html
{% extends 'miscosas/base.html' %}
  {% block menu %}
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/">Inicio</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/alimentadores/">Alimentadores</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/usuarios/">Usuarios</a>
    </li>
  {% endblock %}

  {% block contenido %}
    <h6>La aplicación web llamada "MisCosas" muestra un pequeño blog / foro donde se puede gestionar y compartir contenido de
    diversos sitios web, como es Youtube, Reddit y Last.FM. Los usuarios registrados pueden votar
    y comentar. Además, es posible seleccionar distintos alimentadores.
    Acontinuación, se inserta un video de la demostración de utilización de la página:   </h6>
    <div id = "Videos">
    <iframe width="600" height="350" src="https://www.youtube.com/embed/7Bd33IS3XBE" frameborder="0"
    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <iframe width="600" height="350" src="https://www.youtube.com/embed/Eq5aL_WH8Tc" frameborder="0"
      allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
  {% endblock %}

project/miscosas/templates/miscosas/item.html
{% extends 'miscosas/base.html' %}

  {% block menu %}
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/">Inicio</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/alimentadores/">Alimentadores</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/usuarios/">Usuarios</a>
    </li>
    <li class="nav-item disabled">
      <a class="nav-link" href="/miscosas/info/">Información</a>
    </li>
  {% endblock %}

  {% block contenido %}
    <div  class="content container" id = 'Contenido item'>
      <h2>El item seleccionado es: {{item.titulo}}</h2>
    <a href={{item.enlace}}>{{ item.enlace }}</a>
    {% if "youtube" in item.enlace %}
        <iframe width="933" height="525" src="https://www.youtube.com/embed/{{item.id_item}}"
         frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <h6> {{item.description}}</h6>
    {% endif %}
    {%if "last" in item.enlace %}
          <br><img src={{item.description}} alt="Foto"  width="300">
    {% endif %}
    {%if "reddit" in item.enlace%}
      {{item.description|safe}}
    {% endif %}
      <h5>Votos positivos: {{item.votos_pos}}</h5>
      <h5>Votos negativos: {{item.votos_neg}}</h5>
      <h3>Para más videos del canal del item seleccionado: </h3>
      <li><h5><a href="/miscosas/alimentadores/{{item.alimentador.id_channel}}">
      {{ item.alimentador.titulo }}</a></h5></li>
      <a href={{item.alimentador.enlace}}>{{item.alimentador.enlace }}</a>
    </div>
    <div  class="content container texto" id = 'Comentarios item'>
    {% for comentario in item.comentario_set.all %}
          <br>
          <h3> <img src= "{{ comentario.usuario.foto.url}}"  alt="Foto"  width="50" class="img-rounded rounded-sm">
          <a href="/miscosas/usuarios/{{comentario.usuario.usuario.username}}/">{{comentario.usuario.usuario.username}}</a></h3>
          <h4> {{comentario.cuerpo}}</h4>
          {% if comentario.foto != "no photo" %}
              <img src= "{{ comentario.foto.url}}"  alt="Foto_Comment"  width="100" class="img-rounded rounded-sm">
          {% endif %}
        <br>
        <div  class="small " id = 'Comentario fecha'>
          <h8> {{comentario.fecha}}  </h8>
        </div>
      {% endfor %}
    </div>
    {% if user.is_authenticated %}
    <div id = "formulario_comentarios">
      <form method = "POST">  {% csrf_token %}
        {% if item_votado.voto == 1 %}
          <button class="btn btn-outline-success texto"  id="like" <input type="submit" name="submit" value=like>Like</button>
          <button class="btn btn-danger texto "  id="dislike" <input type="submit" name="submit" value=dislike>Dislike</button>
        {% elif item_votado.voto == -1 %}
          <button class="btn btn-success texto "  id="like" <input type="submit" name="submit" value=like>Like</button>
          <button class="btn btn-outline-danger texto"  id="dislike" <input type="submit" name="submit" value=dislike>Dislike</button>
        {% else %}
          <button class="btn btn-success texto "  id="like" <input type="submit" name="submit" value=like>Like</button>
          <button class="btn btn-danger texto"  id="dislike" <input type="submit" name="submit" value=dislike>Dislike</button>
        {% endif %}
      </form>
      <h7><br><strong>Añadir Comentario</strong></h7>
      <form method="POST" enctype="multipart/form-data"  action="/miscosas/item/{{item.id_item}}/" class="Comment-form">{% csrf_token %}
          {{ form_c.as_p }}
          <input type="hidden" name="comment" id="comment"   value="">
          <button type="submit" class="save btn btn-info texto">Guardar</button>
      </form>
    </div>
    {% endif %}
    Si desea descargar los comentarios de {{item.titulo}} en formato xml: <a href="?format=xml&comment=true">Descarga como fichero XML</a><br>
  {% endblock %}

project/miscosas/templates/miscosas/loggedin.html
{% extends 'miscosas/base.html' %}
{% load static%}
  {% block menu %}
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/">Inicio</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/alimentadores/">Alimentadores</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/usuarios/">Usuarios</a>
    </li>
    <li class="nav-item disabled">
      <a class="nav-link" href="/miscosas/info/">Información</a>
    </li>
  {% endblock %}

  {% block contenido %}
    {% if user.is_authenticated %}
      <h4>Logged in as {{request.user.username}}.</h4>
    {% else %}
      <h4>Se ha cerrado sesión.
        <a href='/admin/'>Login via admin</a>
        o mediante
        <a href='/login'>Login via usuario</a>.
      </h4>
    {% endif %}
    <h4>  Pulse para volver a la página principal.</h4>
    <a type="button" href="/miscosas/" class="btn btn-primary btn-lg btn-block">Pagina principal</a>
  {% endblock %}

project/miscosas/templates/miscosas/usuario.html
{% extends 'miscosas/base.html' %}
  {% block menu %}
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/">Inicio</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/alimentadores/">Alimentadores</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/usuarios/">Usuarios</a>
    </li>
    <li class="nav-item disabled">
      <a class="nav-link" href="/miscosas/info/">Información</a>
    </li>
  {% endblock %}

  {% block contenido %}
    <div class = "container-fluid row" >
      <div class = "col-xs-4 col-sm-4 col-md-3 col-lg-2 col-sm-2" id ="Foto">
        <img src= "{{ usuario.foto.url}}" alt="Foto"  width="100" class="img-rounded rounded-sm">
      </div>
      <div class = "col-xs-5 col-sm-5 col-md-6 col-lg-7 col-sm-7 texto" id ="Nombre">
        <h3>{{usuario.usuario.username}}</h3>
      </div>
      <div class = "col-xs-9 col-md-9 col-lg-9 col-sm-9 texto" id ="Datos votados">
        <br><strong>Items votados:</strong>
        {% for voto in usuario.usuario.item_votados_set.all %}
          <h6><li><a href="/miscosas/item/{{ voto.item.id_item }}">{{voto.item.titulo}}</a>:
            Votos positivos: {{voto.item.votos_pos}} Votos negativos: {{voto.item.votos_neg}}</li></h6>
        {% endfor %}
      </div>
      <div class = "texto" id ="Datos comentarios">
        <br><strong>Items comentados:</strong>
        {% for comentario in usuario.comentario_set.all %}
          <h6><li><a href="/miscosas/item/{{comentario.item.id_item}}">{{comentario.item.titulo}}</a>:
            Votos positivos: {{comentario.item.votos_pos}} Votos negativos: {{comentario.item.votos_neg}}</li></h6>
        {% endfor %}
      </div>
    </div>

    {% if user.is_authenticated %}
      {% if user.username == usuario.usuario.username %}
        <div class = "texto" id ="Modificar perfil">
          <br><h7><strong>Modificar perfil</strong></h7>
          <form method="POST" enctype="multipart/form-data" action="/miscosas/usuarios/{{user.username}}/" class="Perfil-form">{% csrf_token %}
            {{ form_m.as_p }}
            <button type="submit" class="save btn btn-info boton">Guardar</button>
          </form>
        </div>
      {% endif %}
    {% endif %}
  {% endblock %}

project/miscosas/templates/miscosas/usuarios.html
{% extends 'miscosas/base.html' %}
  {% block menu %}
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/">Inicio</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/miscosas/alimentadores/">Alimentadores</a>
    </li>
    <li class="nav-item disabled">
      <a class="nav-link" href="/miscosas/info/">Información</a>
    </li>
  {% endblock %}

  {% block contenido %}
    {% for perfil_datos in perfiles %}
    <div class = "container-fluid row" >
      <div class = "col-xs-4 col-sm-4 col-md-3 col-lg-2" id ="Foto">
        <img src= "{{ perfil_datos.foto.url}}"  alt="Foto"  width="100" class="img-rounded rounded-sm">
      </div>
      <div class = "col-xs-5 col-sm-5 col-md-6 col-lg-7 col-sm-7 texto" id ="Nombre">
        <h3>  <a href="/miscosas/usuarios/{{perfil_datos.usuario.username}}/">{{perfil_datos.usuario.username}}</a></h3>
      </div>
      <div class = " texto" id = "contador de votos y comentarios">
        <h6>Número de votos: {{perfil_datos.usuario.item_votados_set.count}}</h6>
        <h6>Número de comentarios: {{perfil_datos.comentario_set.count}}</h6>
      </div>
    </div>
    {% endfor %}
  {% endblock %}